// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("YC.Bio")>]
[<assembly: AssemblyProductAttribute("YC.Bio")>]
[<assembly: AssemblyDescriptionAttribute("YC Bio research")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "YC.Bio"
    let [<Literal>] AssemblyProduct = "YC.Bio"
    let [<Literal>] AssemblyDescription = "YC Bio research"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
