// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Bio.Search")>]
[<assembly: AssemblyProductAttribute("YC.Bio")>]
[<assembly: AssemblyDescriptionAttribute("Tools for metagenomic assembly processing.")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Bio.Search"
    let [<Literal>] AssemblyProduct = "YC.Bio"
    let [<Literal>] AssemblyDescription = "Tools for metagenomic assembly processing."
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
